version: '3.9'
services:
  user-api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/crud:rw
    # command: "go run cmd/bin/server/main.go"
    # command: "ls -la ."

